name: flutter_dof
description: A new flutter module project.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.4.10
  image: ^2.0.4
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.flutterdof
  assets: 
    - assets/dash.png
    - assets/dashSmall.png
    - assets/emboss.png
    - assets/grayscale.png
    - assets/sepia.png
    - assets/vignette.png
